import pathlib
import subprocess
import shutil
import struct
from typing import List, Dict, Any

# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def process_assets(assets_config: Dict[str, Any],
                   project_dir: pathlib.Path,
                   output_dir: pathlib.Path,
                   byte_swap: bool = False) -> List[str]:
    """
    Process font and image assets declared under `assets:` in the schema.
    Returns list of generated .c file paths (relative to output_dir).

    Schema example:
        assets:
          fonts:
            - name: my_font
              file: fonts/Roboto-Regular.ttf
              size: 20
              bpp: 4          # optional, default 4
              symbols: ""     # optional; empty = full ASCII 32-126
          images:
            - name: logo
              file: images/logo.png
    """
    if not assets_config:
        return []

    generated: List[str] = []
    fonts_cfg  = assets_config.get("fonts", [])
    images_cfg = assets_config.get("images", [])

    for font in fonts_cfg:
        out = _process_font(font, project_dir, output_dir)
        if out:
            generated.append(out)

    for image in images_cfg:
        out = _process_image(image, project_dir, output_dir, byte_swap=byte_swap)
        if out:
            generated.append(out)

    return generated


# ---------------------------------------------------------------------------
# App icon conversion (48×48 CF_TRUE_COLOR_ALPHA)
# ---------------------------------------------------------------------------

def process_icon(icon_path: str,
                 var_name: str,
                 project_dir: pathlib.Path,
                 output_dir: pathlib.Path,
                 byte_swap: bool = False) -> str | None:
    """
    Convert a PNG to a 48×48 lv_img_dsc_t C file with CF_TRUE_COLOR_ALPHA.
    Returns the generated .c filename (relative to output_dir) or None on error.
    The C variable will be ``const lv_img_dsc_t <var_name>``.

    byte_swap: When True (SPI displays with LV_COLOR_16_SWAP=1), write
               RGB565 bytes in big-endian order. When False (DSI/parallel
               displays, desktop sim), write little-endian.
    """
    src = project_dir / icon_path
    if not src.exists():
        print(f"[asset_pipeline] Icon file not found: {src}")
        return None

    try:
        from PIL import Image
    except ImportError:
        print("[asset_pipeline] Pillow not installed — run: pip install pillow")
        return None

    img = Image.open(src).convert("RGBA")
    # Resize to 48×48 if needed
    if img.size != (48, 48):
        print(f"[asset_pipeline] Icon '{icon_path}' is {img.size[0]}×{img.size[1]}, resizing to 48×48")
        img = img.resize((48, 48), Image.LANCZOS)

    w, h = img.size
    pixels = list(img.getdata())

    # CF_TRUE_COLOR_ALPHA: 3 bytes per pixel (RGB565 + alpha)
    # LVGL v8 LV_IMG_CF_TRUE_COLOR_ALPHA = RGB565 (2B) + A (1B) = 3 bytes/px
    # Byte order must match LV_COLOR_16_SWAP setting:
    #   SPI displays (swap=1): big-endian ">H"
    #   DSI/parallel/sim (swap=0): little-endian "<H"
    pack_fmt = ">H" if byte_swap else "<H"
    data = bytearray()
    for r, g, b, a in pixels:
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        data += struct.pack(pack_fmt, rgb565)
        data += bytes([a])

    out_c = output_dir / f"{var_name}.c"
    hex_bytes = ", ".join(f"0x{b:02X}" for b in data)
    c_src = f"""\
// Auto-generated by screenschema asset pipeline — do not edit manually
#include "lvgl.h"

static const uint8_t {var_name}_map[] = {{ {hex_bytes} }};

const lv_img_dsc_t {var_name} = {{
    .header = {{
        .always_zero = 0,
        .w = {w},
        .h = {h},
        .cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    }},
    .data_size = {len(data)},
    .data = {var_name}_map,
}};
"""
    out_c.write_text(c_src)
    print(f"[asset_pipeline] Icon '{icon_path}' → {out_c.name} ({w}×{h} CF_TRUE_COLOR_ALPHA)")
    return out_c.name


# ---------------------------------------------------------------------------
# Font subsetting via lv_font_conv
# ---------------------------------------------------------------------------

def _process_font(font_cfg: dict, project_dir: pathlib.Path, output_dir: pathlib.Path) -> str | None:
    name    = font_cfg.get("name")
    file    = font_cfg.get("file")
    size    = font_cfg.get("size", 16)
    bpp     = font_cfg.get("bpp", 4)
    symbols = font_cfg.get("symbols", "")

    if not name or not file:
        print("[asset_pipeline] Font entry missing 'name' or 'file' — skipping")
        return None

    src = project_dir / file
    if not src.exists():
        print(f"[asset_pipeline] Font file not found: {src}")
        return None

    if not shutil.which("lv_font_conv"):
        print("[asset_pipeline] lv_font_conv not found — install with: npm install -g lv_font_conv")
        print(f"[asset_pipeline] Skipping font '{name}'")
        return None

    out_c = output_dir / f"{name}.c"

    # Default to printable ASCII if no symbols specified
    if not symbols:
        symbols = "".join(chr(i) for i in range(32, 127))

    cmd = [
        "lv_font_conv",
        "--font", str(src),
        "--size", str(size),
        "--bpp",  str(bpp),
        "--symbols", symbols,
        "--format", "lvgl",
        "-o", str(out_c),
        "--force-fast-kern-format",
    ]

    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        print(f"[asset_pipeline] Font '{name}': {src.name} → {out_c.name}")
        return str(out_c)
    except subprocess.CalledProcessError as e:
        print(f"[asset_pipeline] lv_font_conv failed for '{name}': {e.stderr.strip()}")
        return None


# ---------------------------------------------------------------------------
# Image conversion via Pillow → LVGL C array (RGB565 or ARGB8888)
# ---------------------------------------------------------------------------

def _process_image(image_cfg: dict, project_dir: pathlib.Path, output_dir: pathlib.Path,
                   byte_swap: bool = False) -> str | None:
    name   = image_cfg.get("name")
    file   = image_cfg.get("file")
    cf     = image_cfg.get("color_format", "RGB565")  # RGB565 | ARGB8888

    if not name or not file:
        print("[asset_pipeline] Image entry missing 'name' or 'file' — skipping")
        return None

    src = project_dir / file
    if not src.exists():
        print(f"[asset_pipeline] Image file not found: {src}")
        return None

    try:
        from PIL import Image
    except ImportError:
        print("[asset_pipeline] Pillow not installed — run: pip install pillow")
        return None

    img = Image.open(src).convert("RGBA")
    w, h = img.size
    pixels = list(img.getdata())

    out_c = output_dir / f"{name}.c"

    if cf == "ARGB8888":
        data = bytearray()
        for r, g, b, a in pixels:
            data += bytes([b, g, r, a])  # LVGL ARGB8888: B G R A
        cf_enum = "LV_IMG_CF_TRUE_COLOR_ALPHA"
        px_size = 4
    else:  # RGB565 (default)
        pack_fmt = ">H" if byte_swap else "<H"
        data = bytearray()
        for r, g, b, a in pixels:
            rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            data += struct.pack(pack_fmt, rgb565)
        cf_enum = "LV_IMG_CF_TRUE_COLOR"
        px_size = 2

    # Write C source
    hex_bytes = ", ".join(f"0x{b:02X}" for b in data)
    c_src = f"""\
// Auto-generated by screenschema asset pipeline — do not edit manually
#include "lvgl.h"

static const uint8_t {name}_map[] = {{ {hex_bytes} }};

const lv_img_dsc_t {name} = {{
    .header = {{
        .always_zero = 0,
        .w = {w},
        .h = {h},
        .cf = {cf_enum},
    }},
    .data_size = {len(data)},
    .data = {name}_map,
}};
"""
    out_c.write_text(c_src)
    print(f"[asset_pipeline] Image '{name}': {src.name} → {out_c.name} ({w}×{h} {cf})")
    return str(out_c)
